version: '3'
services:
  web:
    image: frojd/phoenix-boilerplate_web
    build: src
    volumes:
      - "./src:/app"
      - "./docker/files/certs:/priv/cert"
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
    env_file: ./docker/config/web.env
  db:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
