name: Test Phoenix-Boilerplate

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy env
        run: cp docker/config/elixir.example.env docker/config/elixir.env

      - name: Build elixir container
        run: docker-compose build elixir

      - name: Run tests
        run: docker-compose run --rm elixir test
